---
apiVersion: v1
kind: Service
metadata:
  name: my-best-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000
  selector:
    my_app: hello-world
---
apiVersion: v1
kind: Service
metadata:
  name: my-public-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: {{ .Values.node_port }}
      targetPort: 4000
  selector:
    my_app: hello-world
