---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-super-config
  labels:
    my_app: hello-world
data:
  my_config_key: my_config_value
  important-file.txt:
    Hello from file!
---
apiVersion: v1
kind: Secret
metadata:
  name: my-super-secret
data:
  my_secret_key: bXlfc2VjcmV0X3ZhbHVl
  secret-file.txt: SGVsbG8gZnJvbSBzZWNyZXQgZmlsZSE=
